version: '3.7'
services:
    db:
        image: mongo
        command: mongod --noauth --port 27017
        env_file:
            - ./.env.dev
        ports:
            - "27017:27017"
    docker-fastapi:
        container_name: docker-fastapi
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file:
            -   ./.env.dev
        restart: always
        ports:
            -   "8000:8000"
        depends_on:
            -   db
    docker-react:
        container_name: docker-react
        build:
            context: ./front-end
            dockerfile: Dockerfile
        restart: always
        ports:
            -   "3000:3000"